# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-18 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
