# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-18 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_image_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='location',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='image',
            name='lng',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
